version: '3'
services:
  app:
    build: ./docker/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - docker/app.env
    command: >
      python hello.py
    restart: "no"
