version: '3'
services:
  app:
    build: ./docker/app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - db-volume:/db
    env_file:
      - docker/app.env
    command: >
      flask run --host=0.0.0.0
    ports:
      - 5000:5000
    restart: "no"
  db:
    build: ./docker/db
    volumes:
      - db-volume:/db
    restart: "no"
volumes:
  db-volume:
