version: '3'
services:
  app:
    build: ./docker/app
    ports:
      - 8080:5000
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - docker/app.env
    command: flask run --host=0.0.0.0
    restart: "no"
